### PR TITLE
Stack upgrade

### PR DESCRIPTION
**Pull request by yoursvivek**
Hey,

It has been a while that servo components of this branch have not been updated. I've upgraded them to latest releases of `html5ever`, `selectors` & `tendril` and recent version of `cssparser`.

cssparser = "0.13"
html5ever = "0.21.0"
selectors = "0.18.0"
tendril = "0.4.0"

### CODE REVIEW

**Comment by yoursvivek** [comment]
The build failed are not what they seem to be. Travis couldn't pull from repo.
```
fatal: unable to access 'https://github.com/programble/scraper.git/': Could not resolve host: github.com
```

**Comment by apiraino** [comment]
Hi @programble 

can we run the CI again on this branch at some point? Probably that was just a temporary DNS resolution error.

It would be great to keep this package alive and updated!

**Comment by programble** [comment]
Yeah sorry, forgot about this.

**Comment by apiraino** [comment]
Hi @programble,

there are indeed new libs, but mostly of them are safe to upgrade. There's only one (`selectors=0.19.0`) that requires a bit of love.

[I've forked your project](https://github.com/apiraino/scraper/tree/update_selector_lib) and I'll try to implement the new, missing methods. I'm pretty new to Rust, so let's see what I can do :^)

**Pull request merged**
